#
# Gitlab configuration
#
# It is possible to use globbing in project names
# Example:
#  - group/*
#  - user/*/documentation
gitlab:
  access:
    gitlab_url: "https://gitlab.com"
    token: "MY_PERSONAL_SECRET_TOKEN"
    # SSL verify
    # Corresponds to verify option in request doc:
    # https://2.python-requests.org/en/master/api/#requests.Session.merge_environment_settings
    # Can be boolean to control whether we verify the ssl server certificate or string in which case it must be a path to CA bundle
    # Default is True
    # If you set it to False, you will get urllib warnings. To supress them, set environment variable:
    # - export PYTHONWARNINGS="ignore:Unverified HTTPS request"
    ssl_verify: True
  projects:
    - rvojcik/example-project
    - rvojcik/group/*
  # Membership attribute used when searching for projects
  # If you want to export all projects from private gitlab instance
  # use False here. In big shared instances or gitlab.com, use True
  membership: True
  # Wait Between Exports
  # How many seconds to wait between projects to export.
  # This is due rate-limiting in gitlab.com
  # https://docs.gitlab.com/ee/user/project/settings/import_export.html#rate-limits
  #
  # If you break the limit, API responds with 429 for your IP address for a while.
  #
  # When you are using this in your private gitlab instance, you can decrease this value, but
  # you need to adjust the api rate limit in your gitlab instance.
  wait_between_exports: 303
  # Maximum Retries
  # Currently not used for anything
  max_tries_number: 12
  # Whether to include archived projects
  include_archived: False
  # List of projects (or patterns) to exclude
  exclude_projects:
    - rvojcik/exclude-me
    - rvojcik/archived/*

#
# Backup configuration
#
backup:
  # Destination of the exports/backups
  destination: "/data/backup"

  # Create separate directory for every project
  project_dirs: False

  # Backup Name template
  # It is possible to use some placeholders in the name
  #   {PROJECT_NAME} - Name of the project with full path
  #   Path slashes are replaced with dashes.
  #   Example:
  #     rvojcik/project1 => rvojcik-project1
  #
  #   {TIME} - Time of the export
  backup_name: "gitlab-com-{PROJECT_NAME}-{TIME}.tar.gz"

  # Time format template
  # Time is constructed by python strftime.
  # backup_time_format can be anything compatible with strftime
  #   Blank spaces are replaced with underscores.
  #   Example:
  #     %Y%m%d %H%M => %Y%m%d_%H%M
  backup_time_format: "%Y%m%d"

  # Retention period (in days)
  # backup files older than this period will be deleted
  # retention_period can be any positive number
  # specify 0 if you want to skip the deletion
  retention_period: 0
